### ISSUE TITLE
SetWH is not defined error

### ISSUE THREAD

**Issue by akuma** [mathjax/MathJax-node#268] opened 2016-10-11 09:41 UTC
sample:

``` bash
page2png < a.html > b.html
```

error:

```
mathjax-node/lib/mj-page.js:834
    SetWH(img,w,h); // work around jsdom bug with width and height CSS
    ^

ReferenceError: SetWH is not defined
```

**Comment by pkra** [comment] 2016-10-11 09:49
Please provide a minimal example HTML file that reproduces the issue.

**Comment by akuma** [comment] 2016-10-11 10:50
I use this example:

```
The well known Pythagorean theorem \(x^2 + y^2 = z^2\) was
proved to be invalid for other exponents.
Meaning the next equation has no integer solutions:

\[ x^n + y^n = z^n \]
```

**Comment by dpvc** [comment] 2016-10-17 02:24
The `SetWH()` function was removed in commit 5f9226c8 (after the jsdom library was patched to properly maintain the svg element's width and height, but apparently not all instances of `SetWH()` were removed.  There appear to be two left, and they should be removed.

**Comment by pkra** [comment] 2016-10-17 07:45
Note also https://github.com/mathjax/MathJax-node/issues/206

**Comment by pkra** [comment] 2016-11-01 21:21
This issue applies only to mj-page which will be moved out of mathjax-node in the next release (see #206). 

Not sure how to tag this issue but I think it can be closed. What do you think @dpvc @zorkow ?

**Comment by dpvc** [comment] 2016-11-02 10:57
Since it is a breaking bug in the current version, it might be worth a hot fix to master even through it doesn't go into develop.

**Comment by pkra** [comment] 2016-11-02 11:05
Ok with me. Could you make a branch that fixes this? We can tag a release from that branch which will get pushed to NPM (thus avoiding re-basing problems for develop).

**Comment by pkra** [comment] 2016-11-11 10:56
@dpvc I've created a branch for this issue (which should **not** be merged I think). All [I did there](https://github.com/mathjax/MathJax-node/blob/issue268/lib/mj-page.js) was remove the two calls to `SetWH` -- is that all?

**Comment by dpvc** [comment] 2016-11-11 11:05
Yes, I think that should do it (I haven't run the code to check, but the `cssText` in the objects created just before the removed calls should include the width and height values.  So removing the `SetWH()` calls should be all there is to it.

**Comment by pkra** [comment] 2016-11-11 12:19
Well, it seems to fix the example above.

@akuma can you try this fix out using  `npm install mathjax/mathjax-node#issue268` (by downloading the `issue268` branch)?

**Comment by akuma** [comment] 2016-11-11 14:16
OK, I will try it later.

**Comment by pkra** [comment] 2016-11-30 08:06
As per F2F, this is ready for release.

**Closed by pkra** 2016-11-30 08:06 UTC
Labels: Accepted, Fixed

**Comment by pkra** [comment] 2016-11-30 08:08
A release off the issue branch has been created https://github.com/mathjax/MathJax-node/releases/tag/0.5.2

**Comment by pkra** [comment] 2016-11-30 08:10
Oops. I screwed up the release. Give me a minut.

**Comment by pkra** [comment] 2016-11-30 08:14
Alright. Release is fixed now.
