### ISSUE TITLE
Suppress ids?

### ISSUE THREAD

**Issue by mattyod** [mathjax/MathJax-node#257] opened 2016-08-09 11:38 UTC
Hi,

I'm using mathjax-node to generate some test fixtures and subsequently run tests against them. Due to the asynchronous way in which the fixtures are generated and the synchronous manner in which the tests are run I'm getting some conflicts in IDs such as: MJXc-Node-XX

I'm struggling a bit to find a way in which I can reset these for each fixture/test or just suppress them entirely. Does such a feature exist?

**Comment by pkra** [comment] 2016-08-09 12:15
Thanks. This is a duplicate of #215 (which is fixed in `develop`).

**Closed by pkra** 2016-08-09 12:15 UTC
Labels: Duplicate

**Comment by mattyod** [comment] 2016-08-09 14:00
Cool thanks. This was a little while ago now will it release any time soon?
