### ISSUE TITLE
tex2svg CLI not getting nested blocks right?

### ISSUE THREAD

**Issue by Pomax** [mathjax/MathJax-node#144] opened 2015-12-30 23:13 UTC
I tried using the `tex2svg` cli utility from the `bin` dir, which works if I use this:
```
$> node node_modules/mathjax-node/bin/tex2svg --extensions 'color' '\\color{blue} E = mc^2'
```
However, it throws a "TeX parse error: extra open brace or missing close brace" if I feed it this:
```
$> node node_modules/mathjax-node/bin/tex2svg --extensions 'color' '{\\color{blue} E} = mc^2'"
```
It seems to not be parsing the nested braces correctly.

The following works, in that it does not generate any errors, but the output it generates is not correct, missing the coloring data that the top-most example generates:
```
$> node node_modules/mathjax-node/bin/tex2svg --extensions 'color' 'a {\\color{blue} E } = mc^2'"
```

**Comment by pkra** [comment] 2015-12-31 12:08
You don't need to escape backslashes on the console and you don't need to load the color extension (it's auto-loaded in mathjax-node).

Anyway, I'm afraid can't produce any issues with these examples. The only thing I notice is that there's a trailing `"` in the second and third example so the best "error" I can come up with is "fixing" that by doing

`$ node node_modules/mathjax-node/bin/tex2svg --extensions 'color' "{\\color{blue} E} = mc^2'"`

-- that  would give an error (`TeX parse error: Prime causes double exponent: use braces to clarify` for the `mc^2'` part) which is expected behavior.

So I'm not sure what you're seeing :(

**Comment by dpvc** [comment] 2015-12-31 20:17
I have the same experience as Peter.  With single-quoted strings, you don't need double backslashes, and the extra `"` was confusing.  WIthout these, both examples work as expected for me.

Peter is also correct that you don't need to load the color extension by hand, since the autoload-all will do that automatically.  (I had through that because there is a version of `\color` already defined that `autoload-all` would not redefine it, but it does.  @pkra, we might want to reconsider that in MathJax-node, since that isn't the default behavior for `\color` in MathJax in the browser.)

Finally, even if you did need to include the extension by hand, it would have to be `--extensions 'TeX/color'` since this allows you to include *any* extension, not just TeX extensions.

**Comment by Pomax** [comment] 2016-01-01 00:25
Probably relevant here, this is on Windows 7 x64 pro with cygwin/unixtools, in the regular windows `cmd` command prompt. All cygwin/unixtools commands are PATH'd so they just work, but it might cause some special edge cases for CLI utilities.

**Comment by pkra** [comment] 2016-02-18 08:56
Closing this for now. Let us know if you have an update that might help us reproduce the issue.

**Closed by pkra** 2016-02-18 08:56 UTC
Labels: Cannot Reproduce
