### ISSUE TITLE
error for missing chars in STIX-Web: tex2svg

### ISSUE THREAD

**Issue by tiarno** [mathjax/MathJax-node#78] opened 2015-03-11 15:32 UTC
When you specify 'STIX-Web' as the SVG font, an error gets thrown for sansserif commas:

    tex2svg --font STIX-Web " \mathsf{i,j,day}" > ~/test.svg
    SVG - Unknown character: U+2C in STIXMathJax_SansSerif
    SVG - Unknown character: U+2C in STIXMathJax_SansSerif

The resulting SVG shows commas; I think they are in Arial. 
If you use the default font 'TeX', there is no error message.

What are the options here, switch to TeX fonts or ignore the errors?

**Comment by dpvc** [comment] 2015-03-11 17:49
The problem is with the data for for the STIX-Web font (and all the web fonts other than the default TeX ones).  The data about where to look for characters in a given font does not include the fallback to the main fonts if the character isn't in the given font.  That needs to be fixed, but currently the situation gives the problem you are reporting.

There are several options.  One is to use

    tex2svg --font STIX-Web "\mathfs{i},\mathfs{j},\mathfs{day}" > ~/test.svg

but that may not be convenient, depending on where your original TeX is coming from.

Alternatively, you can edit the file `node_modules/MathJax/unpacked/jax/output/SVG/fonts/STIX-Web/fontdata.js` in your MathJax-node directory and change 

                fonts: [SANS SERIF],

to 
                fonts: [SANSSERIF,MAIN,MONOSPACE,LATIN,ALPHABETS,MARKS,
                           ARROWS,OPERATORS,SYMBOLS,SHAPES,MISC,VARIANTS,SIZE1],

on line 181.  There will be similar problems with other variants, so you can add the extra data to any other of the variants that you plan to use.  That should make the missing characters fall back on the normal variant when a character is not found in the desired font.

**Comment by pkra** [comment] 2015-03-12 10:10
Should this move upstream?

**Comment by dpvc** [comment] 2015-03-12 13:33
@pkra, this should be part of the font update meta issue in MathJax.

**Comment by tiarno** [comment] 2015-03-12 13:40
I'm testing this code addition as we speak against a database of 30,000 latex equations. So far it looks good, but I will need to add the list to some other variants (bold, italic, etc) to get no error messages.

**Comment by dpvc** [comment] 2015-03-12 13:42
@tiarno, yes, all the variants really should include that list.

**Comment by pkra** [comment] 2015-03-12 16:09
Closed in favor of https://github.com/mathjax/MathJax/issues/1091

**Closed by pkra** 2015-03-12 16:09 UTC
Labels: Upstream
