### ISSUE TITLE
ignoreMMLattributes option not applied

### ISSUE THREAD

**Issue by LuiSlacker** [mathjax/MathJax-node#286] opened 2017-01-04 16:48 UTC
I'm using mathjax-node 0.5.1 to render some serverside svgs. Unfortunately the _ignoreMMLattributes_-option is being ignored. Neither placing it in the mjAPI.config object nor passing it to the typeset function ignored the attribute. 
I'm aware the the  core config option: _ignoreMMLattributes_ controls the MathJax Hub. Is it also available serverside?

It would be nice to be able to pass this option directly to the _typeset_ function once mjAPI is started, since I'd like my attribute(id) to be ignored by some svgs but to be included within others.

See following code snippet
```js
'use strict';

const mjAPI = require('mathjax-node/lib/mj-single.js');

mjAPI.config({
  MathJax: {
    ignoreMMLattributes: {
      id: true
    }
  }
});
mjAPI.start();

module.exports = class MathJaxRenderer {
  static renderMML(mml) {
    return new Promise((resolve, reject) => {
      mjAPI.typeset({
        ignoreMMLattributes: {
          id: true
        },
        math: <mathml>,
        format: 'MathML',
        svg: true
      }, (data) => {
        if (data.errors) reject(data.errors);
        else resolve(data.svg);
      });
    });
  }
};

**Comment by dpvc** [comment] 2017-01-04 21:58
Sorry, the issue is one of bad documentation.  The `ingnoreMMLattributes` object only controls the inclusion of *non-standard* attributes (like RDFa data and `data-*` attributes) on the corresponding HTML or SVG output elements.  The standard attributes like `id` are always processed (and for `id`, that means included in the output).  Indeed, the `id` attributes are crucial to the operation of the CommonHTML and HTML-CSS output renderers, so can not be removed.  

Of course, you can post-process the output and remove the id's yourself.  Can you say more about what you are trying to accomplish?

**Comment by LuiSlacker** [comment] 2017-01-05 12:10
I'm rendering an abstract syntax tree SVG out of content/presentation MathML. Thereby each node's label is an embedded MathJax SVG generated from the nodes presentationMML. 
I'm also rendering the entire formula to the top of the SVG to highlight selected nodes, which indeed leads to duplicated ids within the DOM.

The idea was to exclude the ids within node labels, which is apparently not possible.

<img width="659" alt="ast" src="https://cloud.githubusercontent.com/assets/6152940/21679950/03562358-d347-11e6-81f6-7395dbb40fe2.png">

**Comment by dpvc** [comment] 2017-01-05 17:58
Nice application.

Here's a possible solution for you.  Edit the lib/mj-single.js file and insert

``` javascript
      MathJax.Hub.Register.StartupHook("MathML Jax Ready",function () {
        MathJax.InputJax.MathML.DOMfilterHooks.Add(function (data) {
          var nodes = data.math.querySelectorAll('[id]');
          for (var i = 0, m = nodes.length; i < m; i++) nodes[i].removeAttribute('id');
        });
      });
```

at line 232 (that should be just before the section marked `Adjust the SVG output jax`).  This will have the MathML input jax remove all ID's before processing the MathML, so the SVG output will not include any id's.

You can make the filter include a check for a configuration option if you want to be able to remove id's sometimes and not other times.

**Comment by LuiSlacker** [comment] 2017-01-09 18:28
Thanks @dpvc. I'll try this in a bit!

**Comment by pkra** [comment] 2017-02-23 10:04
Marking this a question and closing it (since it seems to have been answered). 

Feel free to re-open.

**Closed by pkra** 2017-02-23 10:04 UTC
Labels: Question
