### ISSUE TITLE
[CommonHTML] issues with vectors

### ISSUE THREAD

**Issue by roman-spiridonov** [mathjax/MathJax-node#355] opened 2017-08-29 08:08 UTC
I found this issue when updating mathjax-node for [mathjax-node-page](https://github.com/pkra/mathjax-node-page) project.
The latter has a nice [test.html](https://github.com/pkra/mathjax-node-page/blob/master/test/test.html) file.
If you convert it using v1.2.0 for mjnode you will get the following vector overlap issues:
![image](https://user-images.githubusercontent.com/6280272/29810878-37ceab1a-8caa-11e7-8061-2b78718c36f0.png)

Below are the formula contents.
```
    \begin{align}
      \nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} &amp; = \frac{4\pi}{c}\vec{\mathbf{j}} \\
      \nabla \cdot \vec{\mathbf{E}} &amp; = 4 \pi \rho \\
      \nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} &amp; = \vec{\mathbf{0}} \\
      \nabla \cdot \vec{\mathbf{B}} &amp; = 0
    \end{align}
```

UPD: actually I am not sure that it was v1.2.0 update that caused the issue, so changed the issue title.

**Comment by pkra** [comment] 2017-08-29 08:31
Thanks for the report. 

This is a regression due to changes in MathJax v2.7.2 (adding new fonts) and a hardcoded value of `fontURL`.

To workaround this, configure `fontURL` manually to 2.7.2 (instead of 2.7.0).

**Comment by pkra** [comment] 2017-09-05 10:28
Fixed in `develop`.

**Closed by pkra** 2017-09-05 10:28 UTC
Labels: Accepted, Fixed
