### ISSUE TITLE
page2html adds "<style id="MathJax_CHTML_styles">undefined</style>"

### ISSUE THREAD

**Issue by a3nm** [mathjax/MathJax-node#181] opened 2016-02-20 21:22 UTC
The following is added at the end of the `<head>` tag when passing an HTML document through page2html, I am not sure why:

```
<style id="MathJax_CHTML_styles">undefined</style>
```

What is problematic is that this gets added by page2html even if already present, so if page2html is applied again to its own output, the output grows, and becomes invalid (two elements with the same id).

**Comment by pkra** [comment] 2016-02-22 08:29
I cannot reproduce this problem. You might want to share a minimal example exhibiting the problem.

**Comment by a3nm** [comment] 2016-02-22 14:17
I can reproduce it already with the following minimal document, piped through `page2html`:

```
<!DOCTYPE html>
<html><head>
  <title>blah</title>
</head>
<body>
</body></html>
```

I get the following output:

```
<!DOCTYPE html>
<html><head>
  <title>blah</title>
<style id="MathJax_CHTML_styles">undefined</style></head>
<body>

</body></html>
```

Do you get something different?

**Comment by dpvc** [comment] 2016-02-22 14:58
This happens only with an HTML file that doesn't contain any math.  If it has math, then the `undefined` will end up being the styles that are needed for the MathJax output.  It is easy to patch this not to add it when there is no math.

On the other hand, you point out correctly that if you process the output of page2html a second time, you will get a second copy of the style element.  I guess I can have page2html remove the old one before adding it in.

**Comment by a3nm** [comment] 2016-02-22 14:59
OK, thanks for the explanation! Yes, I think it would be cleaner to not add this when there is no math, and to ensure otherwise that page2html does not add a second style element with the same ID as an existing one.

**Comment by dpvc** [comment] 2016-02-22 15:14
The `issue181` branch includes the two fixes discussed above.

**Comment by a3nm** [comment] 2016-02-22 16:01
Thanks a lot! I have applied the patch to my installed version, and I have checked that the useless `<style>` element does not get added to my minimal document, and that applying `page2html` on the output of a run of `page2html` did not add more `<style>` (indeed it results only in changes in whitespace).

So this looks good to me, my only question would then be whether those fixes shouldn't also be done on all bin/page* utilities (and maybe others)? I haven't tried to use them so I don't know, but I don't see why this fix should be specific to `page2html`.

Thanks again!

**Comment by dpvc** [comment] 2016-02-23 06:56
It is specific to `page2html` because that is the one that needs the `<style>` element in the document `<head>`.  The png and mml output don't.  The SVG does, but it enters a proper `<style>` even when the page is blank (though it would be nice if it didn't include any in that case), and running `page2svg` multiple times would cause other problems, so it is not a supported use-case.

I'm not sure what the purpose of running any of the programs multiple times would be.  If the contents of the page has been changes to include more math while still leaving old typeset math on the page, then running `page2html` or `page2svg` will likely lead to duplicate element id's, and if the input is TeX with automatically equation numbers, then it would lead to duplicate equation tags.  One would need to maintain some MathJax state information between calls, which isn't currently being done.  So the iterated invocation on a single file use-case is not really one that we support at the moment.

**Comment by a3nm** [comment] 2016-02-23 07:27
On Mon, Feb 22, 2016 at 10:56:15PM -0800, Davide P. Cervone wrote:
> It is specific to `page2html` because that is the one that needs the
> `<style>` element in the document `<head>`.  The png and mml output
> don't.  The SVG does, but it enters a proper `<style>` even when the
> page is blank (though it would be nice if it didn't include any in
> that case), and running `page2svg` multiple times would cause other
> problems, so it is not a supported use-case.

OK, just thought I'd confirm that this wasn't an oversight. I have no
particular knowledge about the other tools.

> I'm not sure what the purpose of running any of the programs multiple
> times would be.

In my case the "use case" was simply a buggy compilation process that
reapplied page2html to output where it had already been applied. :) So
nothing serious.

> If the contents of the page has been changes to include more math
> while still leaving old typeset math on the page, then running
> `page2html` or `page2svg` will likely lead to duplicate element id's,
> and if the input is TeX with automatically equation numbers, then it
> would lead to duplicate equation tags.  One would need to maintain
> some MathJax state information between calls, which isn't currently
> being done.  So the iterated invocation on a single file use-case is
> not really one that we support at the moment.

I hadn't thought about applying page2html to pages where it had been
applied and then modifications had been added. It's probably a better
use case than my original one, though. :)

As for visible things like equation numbers, I agree this looks messy
and hard to avoid.

As for invisible things like element IDs, I'm not familiar at all with
the internals, but wouldn't this amount to checking which element IDs
already exist on the page, to prevent conflicts between existing
elements and the ones you create?

Actually, in general, a vanilla HTML document could happen to include an
element with an ID like "MJXc-Node-42". In principle, shouldn't
page2html (or MathJax, for that matter) check the existing IDs and
choose a safe prefix that ensures that no conflicts will arise?

**Comment by dpvc** [comment] 2016-02-23 16:28
In principle, yes, the page could already include an ID like the ones used by MathJax.  But in practice, that should be pretty unlikely (unless the page already includes MathJax output).  I suspect that the overhead involved in finding and checking for the duplications is not worth the very low risk of a conflict (though I haven't done any actual tests).  MathJax uses *lots* of internal IDs, so this could add up to significant overhead if individual IDs need to be checked; alternatively, if all IDs are are collected up front and analyzed before doing any typesetting, that would delay the start of typesetting.  Many people use MathJax in editors where typesetting needs to be done for every keystroke.  Since the IDs can change between typeset calls, MathJax would have to do that checking before each typeset, which would negatively impact the update rate for such editors (especially as MathJax output is added to the page, which has lots of IDs that would need to processed).  I just don't see the cost as being worth the potential gain.

**Comment by pkra** [comment] 2016-02-23 16:31
> . I just don't see the cost as being worth the potential gain.

:+1:

**Comment by a3nm** [comment] 2016-02-23 16:43
The question of performance is legitimate, though then one could imagine a setting allowing users to toggle such additional checks to ensure that the output HTML is valid, in cases where it is worth the performance penalty (such as when applying MathJax on the server-side with mathjax-node :)). I agree that this is a very minor issue, though, and I understand you may not want to waste time on it.

Just for fun, though, I wanted to react on the schemes that you discussed and the actual performance cost for in-browser typesetting. I don't know enough JavaScript to know whether one can efficiently check whether some object ID *starts* with a given string. (Specifically, I don't know whether browsers use, e.g., a trie, for the CSS3 selector discussed here http://stackoverflow.com/a/10111688/414272.) If such calls are efficient, though, checking for ID collisions could be done quite efficiently: pick a long prefix; check using such a method that no existing ID starts with the prefix (which should essentially always be the case), which the browser should hopefully do more efficiently than going linearly over all IDs; and then create all the IDs that you want with this prefix and there can be no collision. (In case the initial prefix is not unique and already occurs, just append something to it until it becomes unique, but this should essentially never happen.)

That said, again I agree with you that this is an entirely minor issue. :)

**Comment by tuananhtd** [comment] 2016-03-13 09:22
Hi guys! I have a kind of related question on this topic.
I'm using `page2svg` for server side rendering multiple components in one page. It is because the content is created dynamically and the page is quite large. For each Jax object there is an idential `<style id="MathJax_SVG_styles">` style object. So far everything still works fine but I am wondering: 

1. Is there any potential problem for rendering parts of one page separately? Are those `<style id="MathJax_SVG_styles">` really identical?
2. If thouse stype objects are idential, is there any option I could use to tell MathJax not to include it and let me handle it myself?

**Comment by pkra** [comment] 2016-03-14 09:07
> I'm using page2svg for server side rendering multiple components in one page. It is because the content is created dynamically and the page is quite large. For each Jax object there is an idential <style id="MathJax_SVG_styles"> style object.

There should only be one style element in the head (and definitely not multiple elements using the same id). 

However, I don't see this behavior. Could you share an example that exhibits the problem on the latest release and file a new bug?

**Comment by tuananhtd** [comment] 2016-03-17 07:19
Thank @pkra!
Sorry that I didn't make it clear! This is not a bug. It is totally expected behaviors. In my page I have multiple paragraphs that user can add/remove. Each time the content is updated I use `page2sgv` to render the math server-side. So basically each paragraph that contains math will have that `style` object. I'm just trying to optimize this. Maybe I'm using it wrongly. Hope to hear your thought on this!

**Comment by tuananhtd** [comment] 2016-03-17 07:51
It seem like at least in `page2svg` that style object only do some css resets. Could I safely use `tex2svg` to get the `svg` and then import the Mathjax css resets some where else?

**Comment by dpvc** [comment] 2016-03-19 13:54
The page2* commands are not designed to be run on the same page more than once.  If you do that, you will end up with invalid pages (due to the use of duplicate IDs within the typeset mathematics).  Also, if you have automatic equation numbers, the numbers will not be properly sequenced.  You have already found that the styles will be added multiple times.  The SVG output uses a common SVG element to cache the font paths, and that will not be properly maintained if you use page2svg more than once (unless you disable the global font caching).  There may be other issues as well.

> It seem like at least in page2svg that style object only do some css resets.
> 

Yes, these are mostly to prevent CSS for the rest of the page from bleeding through to the SVG output.
> Could I safely use tex2svg to get the svg and then import the Mathjax css resets some where else?
> 
Yes, you should be able to do that.  In fact, you can probably do without the CSS at all, other than the one for the HREF's within SVG output.

Davide

**Comment by pkra** [comment] 2016-04-11 09:30
Closing this in favor of #206.

**Closed by pkra** 2016-04-11 09:30 UTC
Labels: Accepted
