### ISSUE TITLE
Chinese characters rendered wrong width

### ISSUE THREAD

**Issue by Menci** [mathjax/MathJax-node#322] opened 2017-04-18 11:59 UTC
`$ \text{呵呵} $`, width `html: true`, I got:

```html
<span id="MathJax-Element-1-Frame" class="mjx-chtml">
  <span id="MJXc-Node-638" class="mjx-math">
    <span id="MJXc-Node-639" class="mjx-mrow">
      <span id="MJXc-Node-640" class="mjx-mtext">
        <span class="mjx-char" style="padding-top:0.519em; padding-bottom:0.225em;">
          <span class="mjx-charbox MJXc-TeX-unknown-R" style="padding-bottom:0.3em; width:0.5em;">呵</span>
          <span class="mjx-charbox MJXc-TeX-unknown-R" style="padding-bottom:0.3em; width:0.5em;">呵</span>
        </span>
      </span>
    </span>
  </span>
</span>
```

The width of Chinese characters is wrong.

**Comment by pkra** [comment] 2017-04-18 13:21
Duplicate of https://github.com/mathjax/MathJax-node/issues/299 (see the discussion linked to from there for hacking this manually)

**Closed** 2017-05-04 06:31 UTC
Labels: Duplicate
